version: "3.9"
services:
  devlab:
    build:
      context: .
      args:
        - USER_UID=${UID}
        - USER_GID=${GID}
    container_name: devlab
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./:/home/vscode           # mount entire DEVLAB root
    ports:
      - "5000:5000"
      - "8501:8501"
      - "7860:7860"
      - "8888:8888"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
